<a href="https://colab.research.google.com/github/Matheuslx/pythonComPandas/blob/main/PythonComPandasPokemonDf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

pokemonsDf = pd.read_csv("Pokemon.csv")
display(pokemonsDf)

,#,Name,Type1,Type2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
#Pegando os 10 pokemons mais fortes do tipo de fogo
firePokemons = pokemonsDf.query("Type1 == 'Fire' ")
firePokemons.sort_values(by=['Attack'], ascending=False,inplace = True)
display(firePokemons.head(n=10))

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,#,Name,Type1,Type2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
#Pegando os pokemons mais fortes de cada tipo

tipos = pokemonsDf['Type1'].unique()
pokemonsMaisFortes = []

for tipo in tipos:
  pokemons = pokemonsDf.query(f"Type1 == '{tipo}' ")
  pokemon = pokemons.sort_values(by=['Attack'], ascending=False).head(n=1)
  pokemonsMaisFortes.append(pokemon)

print(pokemonsMaisFortes)

[       #                     Name  Type1 Type2  Total  HP  Attack  Defense  \
511  460  AbomasnowMega Abomasnow  Grass   Ice    594  90     132      105

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
511      132      105     30           4      False  ,        #                   Name Type1     Type2  Total  HP  Attack  Defense  \
279  257  BlazikenMega Blaziken  Fire  Fighting    630  80     160       80

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
279      130       80    100           3      False  ,        #                   Name  Type1 Type2  Total  HP  Attack  Defense  \
141  130  GyaradosMega Gyarados  Water  Dark    640  95     155      109

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
141       70      130     81           1      False  ,        #                     Name Type1     Type2  Total  HP  Attack  Defense  \
232  214  HeracrossMega Heracross   Bug  Fighting    600  80     185      115

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
232       40      105     75           2      False  ,        #     Name   Type1 Type2  Total   HP  Attack  Defense  Sp. Atk  \
313  289  Slaking  Normal   NaN    670  150     160      100       95

     Sp. Def  Speed  Generation  Legendary
313       65    100           3      False  ,        #       Name   Type1     Type2  Total  HP  Attack  Defense  Sp. Atk  \
504  454  Toxicroak  Poison  Fighting    490  83     106       65       86

     Sp. Def  Speed  Generation  Legendary
504       65     85           4      False  ,        #        Name     Type1 Type2  Total  HP  Attack  Defense  Sp. Atk  \
517  466  Electivire  Electric   NaN    540  75     123       67       95

     Sp. Def  Speed  Generation  Legendary
517       85     95           4      False  ,        #                   Name   Type1 Type2  Total   HP  Attack  Defense  \
424  383  GroudonPrimal Groudon  Ground  Fire    770  100     180      160

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
424      150       90     90           3       True  ,        #     Name  Type1 Type2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  \
792  716  Xerneas  Fairy   NaN    680  126     131       95      131       98

     Speed  Generation  Legendary
792     99           6       True  ,        #                 Name     Type1  Type2  Total  HP  Attack  Defense  \
498  448  LucarioMega Lucario  Fighting  Steel    625  70     145       88

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
498      140       70    112           4      False  ,        #                 Name    Type1     Type2  Total   HP  Attack  Defense  \
163  150  MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190      100

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
163      154      100    130           1       True  ,        #       Name Type1 Type2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
454  409  Rampardos  Rock   NaN    495  97     165       60       65       50

     Speed  Generation  Legendary
454     58           4      False  ,        #                 Name  Type1 Type2  Total  HP  Attack  Defense  \
387  354  BanetteMega Banette  Ghost   NaN    555  64     165       75

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
387       93       83     75           3      False  ,        #       Name Type1   Type2  Total   HP  Attack  Defense  Sp. Atk  \
524  473  Mamoswine   Ice  Ground    530  110     130       80       70

     Sp. Def  Speed  Generation  Legendary
524       60     80           4      False  ,        #                   Name   Type1   Type2  Total   HP  Attack  Defense  \
426  384  RayquazaMega Rayquaza  Dragon  Flying    780  105     180      100

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
426      180      100    115           3       True  ,        #             Name Type1 Type2  Total  HP  Attack  Defense  Sp. Atk  \
393  359  AbsolMega Absol  Dark   NaN    565  65     150       60      115

     Sp. Def  Speed  Generation  Legendary
393       60    115           3      False  ,        #                  Name  Type1  Type2  Total  HP  Attack  Defense  \
750  681  AegislashBlade Forme  Steel  Ghost    520  60     150       50

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
750      150       50     60           6      False  ,        #                     Name   Type1 Type2  Total  HP  Attack  Defense  \
702  641  TornadusIncarnate Forme  Flying   NaN    580  79     115       70

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
702      125       80    111           5       True  ]